[package]
name = "valida-lookups"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-air = { workspace = true }
p3-matrix = { workspace = true }
valida-machine = { path = "../machine" }
valida-derive = { path = "../derive" }
valida-util = { path = "../util" }
